spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=2583537f05f1ee
spring.mail.password=2f074ff7177bac

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true